### ISSUE TITLE
improve spacing in vertical mode

### ISSUE THREAD

**Issue by spottedmahn** [dzsquared/MSDocsSidebarCollapser#5]
![image](https://user-images.githubusercontent.com/14079228/142773227-9f7a206b-00da-4aa5-9454-cce641d6fe27.png)
[source](https://docs.microsoft.com/en-us/azure/container-apps/get-started?tabs=bash)

vs

_horizontal mode:_
![image](https://user-images.githubusercontent.com/14079228/142773249-a83ab549-142a-4bcb-88f9-00f37916255a.png)
[source](https://docs.microsoft.com/en-us/azure/container-apps/get-started?tabs=bash)

horizontal looks pretty good.  a little close to the header when wrapped though.

_horizontal mode not wrapped:_
![image](https://user-images.githubusercontent.com/14079228/142773303-2b201c4e-2610-4624-a5b5-9aef9103955c.png)
[source](https://docs.microsoft.com/en-us/azure/container-apps/get-started?tabs=bash)

thoughts? 💭

---

thanks for this extension btw!! 🤝

**Comment by spottedmahn** [comment]
![image](https://user-images.githubusercontent.com/14079228/144928713-cedbfa0c-effd-4f70-b5e4-cfa7606a6bb2.png)

```
margin-bottom: 0.5em;
margin-top: 0.5em;
```

**Comment by dzsquared** [comment]
thanks for the PR!  it did look pretty gross when wrapped before your changes.
